server:
  port: 8080

spring:
  activemq:
    broker-url: tcp://192.168.1.58:61616
    user: admin
    password: xzx12345
    close-timeout: 15s
    in-memory: true
    non-blocking-redelivery: false
    send-timeout: 0
    queue-name: queue1
    topic-name: topic1
  pool:
    enabled: true
    max-connections: 10
    idle-timeout: 30000
  jms:
    pub-sub-domain: true
    template:
      delivery-mode: persistent #持久化